print("Hello")
print("Welcome to Google Cloud")
print("how r u?")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")

